.TH ti-man 1 "13 July 2022" "VERSION 0.0.6" "ti man page"

.Sh NAME
.B Ti
\- simple modal text editor

.SH SYNOPSIS
.B Ti [| FLAGS |] [| FILENAME |]

.SH DESCRIPTION
.B Ti is a terminal based modal text editor built from a fork of Kilo. Uses VT100 escape sequences for keys, as well as only c standard libraries.

.SH OPTIONS
.IP "-v|--version" \-
Print current version of Ti

.IP "-h|--help" \-
Prints help

.SH IN-EDITOR COMMANDS
.IP ":q|quit" \-
Quit, will prompt user to save if file has modifications
.IP ":!q|!quit" \-
Quit, will NOT prompt user to save if file has modifications
.IP ":w|write" \-
Save
.IP ":w new|write new" \-
Rename and open a new copy of current file
.IP ":wq|done" \-
Save and quit
.IP ":set theme <color>" \-
Set theme to red, yellow, green, blue, cyan, magenta, or default
.IP ":set lang <language>" \-
Set language syntax to c, c++, go, rust, javascript, html
.IP ":help" \-
Show some keybinds

.SH FILES
.TP
.I
ti - binary
.TP
.I
tidebug - debug binary
.TP
.I
ti.c - src
.TP
.I
ti.1 - man
.TP
.I
Makefile - make
.TP
.I
LICENSE - license
.TP
.I
README.md - readme

.SH EXAMPLES
.TP
.BI 'Ti [-flag]:'
.TP
.PP
Run ti with 1 or more flags, no scratchpad is opened in this scenario
.TP
.BI 'Ti [filename]:'
.TP
.PP
Run Ti with [filename] opened for editing
.TP
.BI 'Ti:' 
.TP
.PP
Run Ti with an open scratch pad


.SH AUTHOR INFO
.PP
https://www.github.com/tairenfd/Ti
https://www.git.tairenfd.xyz/Ti
